# Generated by Django 4.1.5 on 2023-01-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_booked_seats_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
