# Generated by Django 4.1.5 on 2023-01-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_orgniser_name_alter_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='orgniser_name',
        ),
    ]
